version: '3.7'
services:
    postgres:
        image: "postgres-ssl"
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
        environment:
            POSTGRES_DB: ${SBD_DATABASE}
            POSTGRES_USER: ${SBD_DB_USER}
            POSTGRES_PASSWORD: ${SBD_DB_PASSWORD}
        container_name:
            "dev-postgres"
        volumes:
            - postgresdata:/var/lib/postgresql/data/
        ports:
            - "${SBD_DB_PORT}:${SBD_DB_PORT}"
        restart: unless-stopped
    pgadmin:
        image: "dpage/pgadmin4"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        restart: unless-stopped
    app:
        image: "sports-data-api:latest"
        environment:
            - SD_API_EMAIL_CONFIG=${SBD_API_EMAIL_CONFIG}
            - SD_API_SECRET_KEY=${SBD_API_SECRET_KEY}
        container_name: "sports-data-api"
        ports:
            - "8600:8600"
        depends_on: 
            - database
        restart: always
volumes:
    postgresdata:
        # external: true # tells compose to use existing volume
