version: '3'
services:
  database:
    image: "postgres:11.6"
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name:
      "local_postgres"
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  app:
    image: "sportsbetting-data-api-chi_router:latest"
    environment:
      - SBD_API_EMAIL_CONFIG=${SBD_API_EMAIL_CONFIG}
      - SBD_API_SECRET_KEY=${SBD_API_SECRET_KEY}
    container_name: "sports_data_api"
    ports:
      - "8600:8600"
    depends_on: 
      - database
    restart: always
volumes:
  postgresdata:
    external: true # tells compose to use existing volume