version: '3.7'
services:
    postgres:
        image: "postgres-ssl:latest"
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
        environment:
            POSTGRES_USERNAME: ${SDA_DB_USER}
            POSTGRES_PASSWORD: ${SDA_DB_PASSWORD}
        container_name:
            "dev-postgres"
        volumes:
            - postgresdata:/var/lib/postgresql/data/
        ports:
            - "${SDA_DB_PORT}:${SDA_DB_PORT}"
        restart: unless-stopped
    pgadmin:
        image: "dpage/pgadmin4"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        restart: unless-stopped
    # app:
    #     image: "sports-data-api:latest"
    #     environment:
    #         - SDA_EMAIL_CONFIG=${SDA_EMAIL_CONFIG}
    #         - SDA_SECRET_KEY=${SDA_SECRET_KEY}
    #         - SDA_RDBMS=${SDA_RDBMS}
    #         - SDA_DB_HOST=${SDA_DB_HOST}
    #         - SDA_DB_PORT=${SDA_DB_PORT}
    #         - SDA_DATABASE=${SDA_DATABASE}
    #         - SDA_DB_USER=${SDA_DB_USER}
    #         - SDA_DB_PASSWORD=${SDA_DB_PASSWORD}
    #     container_name: "sports-data-api"
    #     ports:
    #         - "8600:8600"
    #     depends_on: 
    #         - postgres
    #     restart: always
    scraper:
        image: "sports-data-api-scraper:latest"
        environment:
            - SDA_EMAIL_CONFIG=${SDA_EMAIL_CONFIG}
            - SDA_SECRET_KEY=${SDA_SECRET_KEY}
            - SDA_RDBMS=${SDA_RDBMS}
            - SDA_DB_HOST=${SDA_DB_HOST}
            - SDA_DB_PORT=${SDA_DB_PORT}
            - SDA_DATABASE=${SDA_DATABASE}
            - SDA_DB_USER=${SDA_DB_USER}
            - SDA_DB_PASSWORD=${SDA_DB_PASSWORD}
        depends_on:
            - postgres
volumes:
    postgresdata:
        # external: true # tells compose to use existing volume